name: Windows NT/2Kx/XP/2003 CD
tag: nt5
sourceDiskFiles:
  ris:
    OSCHOICE.EXE: /OSChooser/i386/NTLDR
    STARTROM.N12: /OSChooser/i386/Startrom.n12
    STARTROM.COM: /OSChooser/i386/Startrom.com
    WELCOME.OSC: /OSChooser/Welcome.osc
  arch:
    x86: i386
    x64: amd64
    alpha: alpha
  extract:
    osc.cab: /OSChooser/english/
  config:
    SetupData:
      ForceOemHal: 0
      ForceOemSCSI: 0
      
