name: Windows NT CD
tag: nt5
sourceDiskFiles:
  ris:
    OSCHOICE.EX_: /OSChooser/#arch#/NTLDR
    STARTROM.N1_: /OSChooser/#arch#/Startrom.n12
    STARTROM.CO_: /OSChooser/#arch#/Startrom.com
    WELCOME.OS_: /OSChooser/Welcome.osc
    MULTILNG.OS_: /OSChooser/Multilng.osc
  arch:
    x86: i386
    x64: amd64
    alpha: alpha
    ia64: ia64
  extract:
    osc.cab: /OSChooser/#lang#/
  lang:
    englisch:
    german:   
  config:
    SetupData:
      ForceOemHal: 0
      ForceOemSCSI: 0

